CREATE TABLE CUSTOMER(
	CustomerID VARCHAR(10),
	CustomerName VARCHAR(64),
	Email VARCHAR(64),
	Telephone INTEGER,
	PRIMARY KEY(CustomerID)
);

CREATE TABLE OFFICE(
	OfficeID INTEGER,
	PostalCode INTEGER,
	Telephone INTEGER,
	PRIMARY KEY(OfficeID)
);

CREATE TABLE SALE(
	SalesPersonID INTEGER,
	CustomerID VARCHAR(10),
	SaleDate DATE,
	Amount INTEGER,
	PRIMARY KEY(SalesPersonID,CustomerID,SaleDate),
	FOREIGN KEY(SalesPersonID) REFERENCES SALESPERSON(SalesPersonID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(CustomerID) REFERENCES CUSTOMER(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SALESPERSON(
	SalesPersonID INTEGER,
	SalesPersonName VARCHAR(64),
	OfficeID INTEGER,
	PRIMARY KEY(SalesPersonID),
	FOREIGN KEY(OfficeID) REFERENCES OFFICE(OfficeID) ON UPDATE CASCADE ON DELETE CASCADE
);